---
- hosts: all
  become: true
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  import_playbook: ../dynamic-assignments/env-vars.yml
# ---
# - name: Include dynamic variables 
#   hosts: all
#   tasks:
#     - import_playbook: ../static-assignments/common.yml 
#     - import_playbook: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - name: Webserver assignment
#   hosts: webservers
#     - import_playbook: ../static-assignments/uat-webservers.yml

# - name: database assignment
#   hosts: db
#     - import_playbook: ../static-assignments/database.yml

# - name: loadbalancer assignment
#   # host: lb
#   import_playbook: .. /static-assignment/loadbancer.yml
#   when: load_balancer_is_required

